"""create v1 schema

Revision ID: 0ae1912e6091
Revises: 
Create Date: 2026-06-22 17:02:52.741708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ae1912e6091'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pm', 'ba', 'developer', 'client', 'manager', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('project_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='projectstatus'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_groups_project_code'), 'project_groups', ['project_code'], unique=True)
    op.create_table('project_invites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pm', 'ba', 'developer', 'client', 'manager', name='userrole'), nullable=False),
    sa.Column('invite_token', sa.String(), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('invite_sent', 'accepted', 'declined', 'expired', name='invitestatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_invites_invite_token'), 'project_invites', ['invite_token'], unique=True)
    op.create_index(op.f('ix_project_invites_project_id'), 'project_invites', ['project_id'], unique=False)
    op.create_table('project_participants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pm', 'ba', 'developer', 'client', 'manager', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'removed', name='participantstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    op.create_index(op.f('ix_project_participants_project_id'), 'project_participants', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_participants_user_id'), 'project_participants', ['user_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='requirementpriority'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'under_review', 'approved', 'in_development', 'uat', 'completed', 'cancelled', name='requirementstatus'), nullable=False),
    sa.Column('acceptance_criteria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_table('change_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_change', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_impact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technical_impact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timeline_impact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_impact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='changerequestrisklevel'), nullable=False),
    sa.Column('status', sa.Enum('requested', 'impact_analysis', 'pending_approval', 'approved', 'rejected', 'implemented', 'cancelled', name='changerequeststatus'), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_project_id'), 'change_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_change_requests_requirement_id'), 'change_requests', ['requirement_id'], unique=False)
    op.create_table('change_approvals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('change_request_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.Enum('pending', 'approved', 'rejected', 'needs_clarification', name='approvaldecision'), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_approvals_change_request_id'), 'change_approvals', ['change_request_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('requirement_id', sa.BigInteger(), nullable=True),
    sa.Column('change_request_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(requirement_id IS NOT NULL AND change_request_id IS NULL) OR (requirement_id IS NULL AND change_request_id IS NOT NULL)', name='chk_comment_target'),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_change_request_id'), 'comments', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_comments_requirement_id'), 'comments', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_requirement_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_change_request_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_change_approvals_change_request_id'), table_name='change_approvals')
    op.drop_table('change_approvals')
    op.drop_index(op.f('ix_change_requests_requirement_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_project_id'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_project_participants_user_id'), table_name='project_participants')
    op.drop_index(op.f('ix_project_participants_project_id'), table_name='project_participants')
    op.drop_table('project_participants')
    op.drop_index(op.f('ix_project_invites_project_id'), table_name='project_invites')
    op.drop_index(op.f('ix_project_invites_invite_token'), table_name='project_invites')
    op.drop_table('project_invites')
    op.drop_index(op.f('ix_project_groups_project_code'), table_name='project_groups')
    op.drop_table('project_groups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
