"""Add core CRMS ML fields and ActivityLog

Revision ID: 50a9c0bf86de
Revises: 6a43a6903aec
Create Date: 2026-06-30 23:52:02.417787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50a9c0bf86de'
down_revision: Union[str, None] = '6a43a6903aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_project_id'), 'activity_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.add_column('change_requests', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('change_requests', sa.Column('impact', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('change_requests', sa.Column('reviewed_by_id', sa.BigInteger(), nullable=True))
    op.add_column('change_requests', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('change_requests', sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('change_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('change_requests', 'requirement_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_foreign_key(None, 'change_requests', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('change_requests', 'risk_level')
    op.drop_column('change_requests', 'business_impact')
    op.drop_column('change_requests', 'technical_impact')
    op.drop_column('change_requests', 'timeline_impact')
    op.drop_column('change_requests', 'requested_change')
    op.drop_column('change_requests', 'cost_impact')
    op.add_column('requirements', sa.Column('complexity', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('requirements', sa.Column('business_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('requirements', sa.Column('estimated_effort_days', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'estimated_effort_days')
    op.drop_column('requirements', 'business_value')
    op.drop_column('requirements', 'complexity')
    op.add_column('change_requests', sa.Column('cost_impact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('change_requests', sa.Column('requested_change', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('change_requests', sa.Column('timeline_impact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('change_requests', sa.Column('technical_impact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('change_requests', sa.Column('business_impact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('change_requests', sa.Column('risk_level', postgresql.ENUM('low', 'medium', 'high', name='changerequestrisklevel'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'change_requests', type_='foreignkey')
    op.alter_column('change_requests', 'requirement_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('change_requests', 'updated_at')
    op.drop_column('change_requests', 'rejection_reason')
    op.drop_column('change_requests', 'reviewed_at')
    op.drop_column('change_requests', 'reviewed_by_id')
    op.drop_column('change_requests', 'impact')
    op.drop_column('change_requests', 'description')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_project_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
