"""Add requirement review fields

Revision ID: 6a43a6903aec
Revises: e878c8064c33
Create Date: 2026-06-30 23:41:30.489541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a43a6903aec'
down_revision: Union[str, None] = 'e878c8064c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('reviewed_by_id', sa.BigInteger(), nullable=True))
    op.add_column('requirements', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('requirements', sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('requirements', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'requirements', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.drop_column('requirements', 'updated_at')
    op.drop_column('requirements', 'rejection_reason')
    op.drop_column('requirements', 'reviewed_at')
    op.drop_column('requirements', 'reviewed_by_id')
    # ### end Alembic commands ###
