"""Add completion time fields to requirement

Revision ID: 7e06af246e40
Revises: 3f5ef43f4e77
Create Date: 2026-07-06 18:00:48.854717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e06af246e40'
down_revision: Union[str, None] = '3f5ef43f4e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('ai_estimated_completion_days', sa.Float(), nullable=True))
    op.add_column('requirements', sa.Column('ai_completion_min_days', sa.Float(), nullable=True))
    op.add_column('requirements', sa.Column('ai_completion_max_days', sa.Float(), nullable=True))
    op.add_column('requirements', sa.Column('ai_completion_confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('requirements', sa.Column('ai_completion_model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('requirements', sa.Column('completion_estimation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('requirements', sa.Column('effort_overridden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'effort_overridden')
    op.drop_column('requirements', 'completion_estimation_reason')
    op.drop_column('requirements', 'ai_completion_model_used')
    op.drop_column('requirements', 'ai_completion_confidence')
    op.drop_column('requirements', 'ai_completion_max_days')
    op.drop_column('requirements', 'ai_completion_min_days')
    op.drop_column('requirements', 'ai_estimated_completion_days')
    # ### end Alembic commands ###
