"""Add AI tracking fields to Requirement

Revision ID: 8a6e98551d34
Revises: 50a9c0bf86de
Create Date: 2026-07-06 16:00:35.323887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a6e98551d34'
down_revision: Union[str, None] = '50a9c0bf86de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('ai_suggested_priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('requirements', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('requirements', sa.Column('priority_overridden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'priority_overridden')
    op.drop_column('requirements', 'ai_confidence')
    op.drop_column('requirements', 'ai_suggested_priority')
    # ### end Alembic commands ###
