import sqlmodel
"""Update ActivityLog schema

Revision ID: 8d4bdf2ee71b
Revises: 8a6e98551d34
Create Date: 2026-07-06 17:00:02.250505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4bdf2ee71b'
down_revision: Union[str, None] = '8a6e98551d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('requirement_id', sa.BigInteger(), nullable=True))
    op.add_column('activity_logs', sa.Column('change_request_id', sa.BigInteger(), nullable=True))
    op.add_column('activity_logs', sa.Column('actor_id', sa.BigInteger(), nullable=True))
    op.add_column('activity_logs', sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('activity_logs', sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('activity_logs', 'project_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index('ix_activity_logs_action_type', table_name='activity_logs')
    op.drop_index('ix_activity_logs_user_id', table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_change_request_id'), 'activity_logs', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_requirement_id'), 'activity_logs', ['requirement_id'], unique=False)
    op.drop_constraint('activity_logs_user_id_fkey', 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'change_requests', ['change_request_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity_logs', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'activity_logs', 'requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activity_logs', 'action_type')
    op.drop_column('activity_logs', 'user_id')
    op.drop_column('activity_logs', 'description')
    op.drop_column('activity_logs', 'entity_type')
    op.drop_column('activity_logs', 'entity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activity_logs', sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activity_logs', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activity_logs', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('activity_logs', sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key('activity_logs_user_id_fkey', 'activity_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_activity_logs_requirement_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_change_request_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.create_index('ix_activity_logs_user_id', 'activity_logs', ['user_id'], unique=False)
    op.create_index('ix_activity_logs_action_type', 'activity_logs', ['action_type'], unique=False)
    op.alter_column('activity_logs', 'project_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('activity_logs', 'message')
    op.drop_column('activity_logs', 'action')
    op.drop_column('activity_logs', 'actor_id')
    op.drop_column('activity_logs', 'change_request_id')
    op.drop_column('activity_logs', 'requirement_id')
    # ### end Alembic commands ###
