"""Add rule-based effort fields and remove ML completion fields

Revision ID: f6ad57c37b94
Revises: 7e06af246e40
Create Date: 2026-07-06 19:17:27.765162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ad57c37b94'
down_revision: Union[str, None] = '7e06af246e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('suggested_effort_min_days', sa.Float(), nullable=True))
    op.add_column('requirements', sa.Column('suggested_effort_max_days', sa.Float(), nullable=True))
    op.add_column('requirements', sa.Column('suggested_effort_recommended_days', sa.Float(), nullable=True))
    op.add_column('requirements', sa.Column('suggested_effort_reason', sa.String(), nullable=True))
    op.drop_column('requirements', 'ai_completion_max_days')
    op.drop_column('requirements', 'ai_completion_model_used')
    op.drop_column('requirements', 'ai_estimated_completion_days')
    op.drop_column('requirements', 'ai_completion_confidence')
    op.drop_column('requirements', 'ai_completion_min_days')
    op.drop_column('requirements', 'completion_estimation_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('completion_estimation_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('requirements', sa.Column('ai_completion_min_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requirements', sa.Column('ai_completion_confidence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('requirements', sa.Column('ai_estimated_completion_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requirements', sa.Column('ai_completion_model_used', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('requirements', sa.Column('ai_completion_max_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('requirements', 'suggested_effort_reason')
    op.drop_column('requirements', 'suggested_effort_recommended_days')
    op.drop_column('requirements', 'suggested_effort_max_days')
    op.drop_column('requirements', 'suggested_effort_min_days')
    # ### end Alembic commands ###
